export default {
  "BTC/USD": "Coinbase",
  "BTC/ETH": "Bitfinex",
  "BTC/BNB": "Bitfinex",
  "BTC/TRX": "Bitfinex",
  "BTC/LTC": "Bitfinex",
  "ETH/USD": "Coinbase",
  "ETH/BTC": "Coinbase",
  "ETH/BNB": "Bitfinex",
  "ETH/TRX": "Bitfinex",
  "ETH/LTC": "Bitfinex",
};

export const data = [
  {
    symbol: "BTC/USD",
    full_name: "BTC/USD",
    description: "description",
    exchange: "-",
    type: "type",
  },
  {
    symbol: "BTC/ETH",
    full_name: "BTC/ETH",
    description: "description",
    exchange: "-",
    type: "type",
  },
  {
    symbol: "BTC/BNB",
    full_name: "BTC/BNB",
    description: "description",
    exchange: "-",
    type: "type",
  },
  {
    symbol: "BTC/TRX",
    full_name: "BTC/TRX",
    description: "description",
    exchange: "-",
    type: "type",
  },
  {
    symbol: "BTC/LTC",
    full_name: "BTC/LTC",
    description: "description",
    exchange: "-",
    type: "type",
  },
  {
    symbol: "ETH/USD",
    full_name: "ETH/USD",
    description: "description",
    exchange: "-",
    type: "type",
  },
  {
    symbol: "ETH/BTC",
    full_name: "ETH/BTC",
    description: "description",
    exchange: "-",
    type: "type",
  },
  {
    symbol: "ETH/BNB",
    full_name: "ETH/BNB",
    description: "description",
    exchange: "-",
    type: "type",
  },
  {
    symbol: "ETH/TRX",
    full_name: "ETH/TRX",
    description: "description",
    exchange: "-",
    type: "type",
  },
  {
    symbol: "ETH/LTC",
    full_name: "ETH/LTC",
    description: "description",
    exchange: "-",
    type: "type",
  },
];
